name: Build Vue.js App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'
      
      - name: Install dependencies
        run: npm install
        working-directory: client
      
      - name: Build Vue.js project
        run: npm run build
        working-directory: client

      - name: Remove the current content from the app folder
        run: rm -r server/public/app/*
      
      - name: Move dist folder to public
        run: mv client/dist/* server/public/app

      - name: Commit and push Vue.js build
        uses: EndBug/add-and-commit@v9
        with:
          add: 'server/public/app'
          message: 'Commit Vue.js build'
          push: true
          default_author: github_actions