name: Build and Deploy App

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy ⛏🚀
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Use Node.JS
      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'
      
      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: client
      
      # Build Vue.js project  
      - name: Build Vue.js project
        run: npm run build
        working-directory: client
      
      # Remove current content of public folder
      - name: Remove current content of public folder
        run: rm -rf server/public/app/*
      
      # Move dist folder to public
      - name: Move dist folder to public
        run: mkdir -p server/public/app && mv client/dist/* server/public/app

      # Upload files via FTP
      - name: Deploy app via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./server/ # Local project directory
          server-dir: /var/www/secret-santa/
          protocol: ftp # Protocol
          exclude: | # Exclude files
            .env